name: PR Build

defaults:
  run:
    shell: bash

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "test/**"

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate set "debug_enabled"'
        type: boolean
        required: false
        default: false

permissions:
  contents: read

jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      - run: echo "GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME"

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-ddev-executables
          path: path/to/artifact/world.txt
      - name: Upload macos-amd64 binary
        uses: actions/upload-artifact@v4
        with:
          name: ddev-macos-amd64
          path: path/to/artifact/world.txt
      - name: Upload macos-arm64 binary
        uses: actions/upload-artifact@v4
        with:
          name: ddev-macos-arm64
          path: path/to/artifact/world.txt
      - name: Upload linux-arm64 binary
        uses: actions/upload-artifact@v4
        with:
          name: ddev-linux-arm64
          path: path/to/artifact/world.txt
      - name: Upload linux-amd64 binary
        uses: actions/upload-artifact@v4
        with:
          name: ddev-linux-amd64
          path: path/to/artifact/world.txt
      - name: Upload windows_amd64 installer
        uses: actions/upload-artifact@v4
        with:
          name: ddev-windows-amd64-installer
          path: path/to/artifact/world.txt
